language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
  global:
    - PACKAGE="grenier"
    - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
  matrix:
    - DISTRO=debian-unstable OCAML_VERSION=4.09.0
    - DISTRO=alpine OCAML_VERSION=4.04.0
    - DISTRO=alpine OCAML_VERSION=4.05.0
    - DISTRO=alpine OCAML_VERSION=4.06.1
    - DISTRO=alpine OCAML_VERSION=4.07.1
    - DISTRO=alpine OCAML_VERSION=4.08.1
    - DISTRO=alpine OCAML_VERSION=4.09.0
    - DISTRO=alpine OCAML_VERSION=4.10.0
